const prendas = [
  "Faça uma dança sensual para o parceiro.",
  "Faça um striptease completo e dance nu(a) por 2 minutos.",
"Deixe que alguém te amarre e te provoque sem piedade por 3 minutos.",
"Simule estar sendo penetrado(a) violentamente enquanto olha para quem escolher.",
"Beije e morda intensamente o pescoço de quem estiver mais perto.",
"Fique nu(a) e de quatro na frente de todos por 1 minuto.",
"Deixe que alguém passe um cubo de gelo pelo seu corpo até derreter.",
"Simule um orgasmo múltiplo, gemendo e se contorcendo até todos acreditarem.",
"De tapas e mordidas nas coxas ou nádegas do parceiro.",
"Deixe que alguém acaricie sua parte íntima por cima da roupa por 30 segundos.",
"Fique de olhos vendados e permita que te provoquem por 3 minutos.",
"Fique sentado(a) no colo de quem escolher e simule uma transa intensa.",
"Lamba a parte do corpo que mais te excita em alguém.",
"Encoste seu corpo nu no de alguém e simule sua posição sexual favorita.",
"Beije, morda ou lamba quem quiser, onde quiser.",
"Fique sem roupa até o final do jogo, só com as mãos cobrindo.",
"Deixe alguém puxar seu cabelo e te dar um tapa bem forte.",
"Deixe alguém lamber e morder sua orelha até você gemer.",
"Simule estar implorando por prazer e se contorça enquanto faz isso.",
"Deixe que te algemem ou amarrem e te provoquem até você não aguentar.",
"Escolha alguém para fazer carícias íntimas escondido dos outros.",
"Fique nu(a) e fique abraçado(a) com quem quiser por 2 minutos.",
"Simule que está realizando sexo oral em quem escolher.",
"Deixe alguém te provocar com um vibrador ou objeto qualquer.",
"Imite sons de prazer enquanto outra pessoa finge te penetrar.",
"Simule uma cena de dominação total, com ordens explícitas.",
"Beije intensamente quem escolher, com mordidas e gemidos.",
"Deixe que te provoquem com mordidas e beijos até você perder o controle.",
"Faça uma dança erótica completamente nu(a).",
"Deixe alguém te puxar pela cintura e te dominar como quiser.",
"Fique de quatro e deixe que alguém simule te penetrar.",
"Deixe alguém te provocar enquanto você tenta resistir sem gemer.",
"Simule estar tendo um orgasmo enquanto alguém sussurra no seu ouvido.",
"Escolha alguém para te provocar com palavras sujas bem de perto.",
"Fique totalmente nu(a) e deixe que alguém acaricie seu corpo.",
"Deixe que alguém passe as mãos pelo seu corpo como quiser.",
"Deixe alguém puxar seu cabelo e te provocar ao mesmo tempo.",
"Encoste sua boca no pescoço de quem quiser e diga: 'não aguento mais'.",
"Deixe alguém lamber sua barriga ou coxa até você arrepiar.",
"Fique sentado(a) no colo de quem escolher e se provoquem mutuamente.",
"Deixe que te vendem e te provoquem com carícias ousadas.",
"Deixe alguém simular estar te penetrando na frente de todos.",
"Encoste sua testa na de quem quiser e diga: 'me domina'.",
"Escolha alguém para te provocar escondido(a) dos outros.",
"Fique deitado(a) e deixe que alguém suba em cima de você.",
"Simule que está sendo dominado(a) e implore por mais.",
"Beije quem escolher por pelo menos 30 segundos sem parar.",
"Deixe alguém acariciar sua parte íntima sob a roupa por 1 minuto.",
"Fique de quatro e deixe que alguém te provoque como quiser.",
"Deixe alguém te dar um tapa na parte do corpo que quiser.",
"Fique completamente nu(a) e dance para quem escolher.",
"Simule estar realizando sexo oral até todos acreditarem.",
"Deixe alguém morder sua parte preferida do corpo.",
"Encoste-se ao corpo de alguém e provoquem-se mutuamente.",
"Deixe alguém te provocar com mordidas e lambidas pelo corpo.",
"Escolha alguém para simular uma cena sexual contigo.",
"Fique com os olhos fechados e deixe que alguém te provoque por 3 minutos.",
"Deixe que te provoquem enquanto você tenta resistir sem gemer.",
"Fique sem roupa e apenas de joelhos, olhando para quem quiser.",
"Escolha alguém para simular que está te penetrando violentamente.",
"Deixe alguém lamber e morder o seu abdômen ou coxa.",
"Fique nu(a) e deixe alguém te provocar com um objeto gelado.",
"Deixe que te amarrem e sussurrem coisas explícitas no seu ouvido.",
"Beije ou lamba quem quiser, na parte do corpo que mais te excita.",
"Fique completamente vulnerável e deixe que te provoquem sem piedade.",
"Deixe alguém te provocar com tapas e mordidas até você não aguentar mais.",
"Simule estar sendo penetrado(a) brutalmente enquanto olha para quem escolher.",
"Deixe alguém puxar seu cabelo e te beijar forte ao mesmo tempo.",
"Fique completamente nu(a) e escolha alguém para te provocar.",
"Simule estar sendo dominado(a) e diga 'eu sou todo(a) seu(a)'.",
"Deixe alguém lamber seu pescoço enquanto você geme.",
"Deixe alguém provocar sua parte mais sensível com mordidas.",
"Simule estar implorando por prazer enquanto se contorce.",
"Fique de olhos vendados e deixe alguém te provocar sem saber quem é.",
"Deixe alguém simular estar te amarrando e te dominando.",
"Beije, lamba ou morda quem escolher, da forma mais intensa possível.",
"Simule estar realizando sexo com quem quiser, até todos acreditarem.",
"Deixe que alguém te provoque com palavras sujas bem de perto.",
"Fique completamente nu(a) e deixe alguém escolher como te provocar.",
"Encoste seu corpo no de quem quiser e provoquem-se mutuamente.",
"Simule uma cena de submissão total e deixe que alguém te domine.",
"Deixe alguém lamber e morder o local mais sensível do seu corpo.",
"Fique completamente nu(a) e provoque quem quiser com uma dança erótica.",
"Escolha alguém para simular estar te penetrando na sua posição favorita.",
"Deixe que te vendem e te provoquem por todo o corpo sem saber quem é.",
"Deixe alguém lamber sua coxa ou barriga até você gemer.",
"Encoste sua boca na orelha de quem quiser e diga: 'me faz perder o controle'.",
  "Poste uma indireta provocante nos stories.",
  "Dê um beijo demorado no pescoço do parceiro.",
  "Conte ao parceiro uma fantasia que nunca revelou.",
  "Tire uma peça de roupa e entregue ao parceiro",
  "Envie uma mensagem provocante para o parceiro, mesmo estando juntos.",
  "Dance de forma provocante para o parceiro.",
  "Proponha uma nova posição ou fantasia para realizarem juntos.",
  "Deixe o parceiro dar um beijo onde quiser.",
  "Me dê um beijo de tirar o fôlego, como se fosse o último.",
"Sente no meu colo e me provoque por um minuto, sem dizer nada.",
"Me mande uma mensagem provocante agora, mesmo estando aqui.",
"Fique bem perto de mim, mas sem me beijar, até eu ceder.",
"Mostre qual parte do seu corpo quer que eu beije agora.",
"Faça um strip-tease de no mínimo 1 min",
"Me mande uma mensagem extremamente provocante para eu ler depois.",
"Me puxe e me beije onde quiser, com intensidade.",
"Tire uma peça de roupa, agora.",  
"Deixe eu te beijar onde eu quiser.",  
"Mande uma mensagem safada, como se fosse um convite para hoje à noite.",  
"Sente no meu colo e me beije de olhos fechados.",  
"Faça um strip tease de pelo menos 1 minuto.",  
"Fique só de roupa íntima por 5 minutos.",  
"Encoste seu corpo no meu e simule uma dança erótica.",  
"Deixe eu vendar seus olhos e explorar seu corpo.",  
"Fale, olhando nos meus olhos: 'Hoje eu sou seu/sua completamente'.",  
"Deixe eu amarrar suas mãos (ou simule como se fosse).",  
"Me beije como se fôssemos fazer amor agora.",  
"Faça um elogio erótico bem explícito sobre o meu corpo.",  
"Fique de joelhos na minha frente e me provoque só com o olhar.",  
"Me provoque mordendo ou lambendo os seus próprios lábios.",  
"Encoste sua boca na minha orelha e diga: 'Quero te fazer gozar'.",  
"Me deixe tocar em qualquer parte do seu corpo, sem restrições.",  
"Simule como me puxaria para a cama, sem cerimônia.",  
"Deixe eu sussurrar algo bem sujo no seu ouvido e você responde: 'Quero'.",  
"Morda ou beije suavemente uma parte íntima, discretamente.",  
"Me provoque ficando colado(a) em mim, sem falar nada.",  
"Me olhe fixamente e diga: 'Eu vou te enlouquecer'.",  
"Me mostre uma posição sexual que quer experimentar.",  
"Encoste sua boca na minha barriga e simule um beijo ou mordida.",  
"Me abrace e me aperte bem forte contra você.",  
"Passe a mão pelo seu corpo, como se fosse eu te tocando.",  
"Deixe eu escolher onde quero te provocar com um beijo.",  
"Sente-se no meu colo e provoque, rebolando suavemente.",  
"Encoste sua testa na minha e diga: 'Você não imagina o que eu quero fazer com você'.",  
"Me beije até perder o fôlego.",  
"Diga bem no meu ouvido: 'Hoje você é meu/minha, inteiro(a)'.",  
"Tire uma peça de roupa agora.",
"Simule um striptease completo.",
"Beije a parte do corpo de quem escolher.",
"Descreva sua fantasia mais obscura em voz alta.",
"Envie uma mensagem explícita para o(a) crush.",
"Fique de roupa íntima até a próxima rodada.",
"Simule um orgasmo até todos acreditarem.",
"Deixe alguém lamber ou morder qualquer parte do seu corpo.",
"Beije o pescoço de quem quiser de forma provocante.",
"Imite uma cena de sexo de filme pornô.",
"Deixe alguém te vendar e provocar por 1 minuto.",
"Escolha alguém para te abraçar por trás e te apertar.",
"Dance no colo de quem quiser.",
"Sente no colo de alguém até a próxima rodada.",
"Passe gelo na sua barriga e deixe alguém lamber.",
"Deixe alguém morder sua orelha agora.",
"Encoste o corpo no de alguém e simule uma dança bem sensual.",
"Deixe alguém escolher onde te beijar.",
"Beije quem quiser da forma mais quente que conseguir.",
"Escolha alguém para te dar um beijo de cinema.",
"Fique de quatro e deixe alguém te dar um tapa.",
"Beije o abdômen ou cintura de quem escolher.",
"Encoste o rosto na pessoa ao lado e sussurre: 'te desejo'.",
"Escolha alguém para fazer um carinho íntimo por cima da roupa.",
"Deixe alguém te provocar com palavras sujas.",
"Simule estar sendo dominado(a) por quem quiser.",
"Simule que está fazendo sexo com almofadas.",
"Escolha alguém para acariciar seu pescoço.",
"Deixe alguém amarrar suas mãos por uma rodada.",
"Encoste sua testa na de alguém e diga: 'te quero muito'.",
"Beije ou morda a clavícula de quem escolher.",
"Deixe alguém lamber sua nuca.",
"Sussurre no ouvido de alguém: 'te desejo agora'.",
"Encoste no corpo de alguém e provoque sem falar nada.",
"Deixe alguém te puxar pela cintura ou cabelo.",
"Beije ou acaricie a coxa de quem quiser.",
"Simule um gemido até alguém acreditar que é real.",
"Fique sem camisa até o final da rodada.",
"Deixe alguém te provocar com um tapa ou mordida.",
"Sente no colo de alguém e abrace apertado.",
"Deixe alguém lamber seu pescoço por 10 segundos.",
"Escolha alguém para acariciar sua cintura ou coxa.",
"Beije a parte do corpo que quiser da pessoa à sua esquerda.",
"Fique de olhos fechados e deixe alguém te provocar como quiser.",
"Simule estar dominando ou sendo dominado(a) por quem escolher.",
"Beije ou morda os lábios de quem quiser.",
"Passe a língua na orelha de quem quiser.",
"Deixe alguém te abraçar bem apertado.",
"Escolha alguém e fique abraçado até o fim do jogo.",
"Simule um beijo selvagem em quem quiser.",
"Escolha alguém para morder sua cintura.",
"Encoste seu corpo no de quem quiser por um minuto.",
"Beije ou acaricie suavemente as costas de quem escolher.",
"Escolha alguém para fazer um carinho íntimo por cima da roupa.",
"Deixe alguém lamber ou beijar sua barriga.",
"Sente no colo de alguém e dance sensualmente.",
"Deixe alguém te provocar com palavras sujas no ouvido.",
"Beije a nuca de quem quiser bem lentamente.",
"Encoste sua boca na orelha de quem quiser e sussurre 'me pega'.",
"Simule estar se despindo para alguém.",
"Deixe alguém escolher como te provocar por um minuto.",
"Simule estar tendo uma transa intensa agora.",
"Beije ou lamba o pescoço de quem quiser.",
"Escolha alguém para acariciar sua parte favorita do corpo.",
"Fique de roupa íntima até o final do jogo.",
"Escolha alguém para segurar sua cintura com força.",
"Beije ou morda o ombro de quem quiser.",
"Simule uma dança de pole dance.",
"Deixe alguém escolher uma peça de roupa sua para tirar.",
"Beije ou acaricie a coxa de quem está à sua frente.",
"Simule estar sendo puxado(a) para um beijo quente.",
"Escolha alguém para lamber sua nuca ou pescoço.",
"Encoste seu corpo inteiro no de quem quiser.",
"Beije o abdômen de quem quiser bem lentamente."
];